### ISSUE TITLE
Packaging introduces index.js without(vite version：3.2.5)

### ISSUE THREAD

**Issue by meislisha** [jacekkarczmarczyk/importmap-plugin#3]
![image](https://user-images.githubusercontent.com/30792385/225528896-7ad4e610-d55f-45c1-9e38-f53c7a2a8fb7.png)

**Comment by jacekkarczmarczyk** [comment]
That's what the package is for

**Comment by meislisha** [comment]
**But the page reference will give an error**

![image](https://user-images.githubusercontent.com/30792385/225540452-95c7c073-b8b7-4e0f-8d64-3a3ac993455d.png)

**Comment by jacekkarczmarczyk** [comment]
I can't debug an image, feel free to provide a minimal runnable reproduction

**Comment by jacekkarczmarczyk** [comment]
I think I might have actually reproduced the issue in my project, I'll keep #2 open though as it may seem to be the same problem
